###
# @name createUser
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "coder_man",
  "email": "coder@example.com"
}

###
# @name createPost
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My New Code Snippet",
    "content": "This is a great code example.",
    "authorId": 3
}

###
# @name getPosts
GET http://localhost:3000/posts

###
# @name getPostById
GET http://localhost:3000/posts/3

###
# @name updatePost
PUT http://localhost:3000/posts/3
Content-Type: application/json

{
  "title": "Updated Code Snippet",
  "content": "This is an updated code example.",
  "authorId": 3
}
